// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
        return linux;
=======
=======
>>>>>>> Stashed changes
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLdlOvy4qpLtIQf49KJCdhd8cAnhS6RPk',
    appId: '1:136251052813:web:8f939ca7b3354c5604d644',
    messagingSenderId: '136251052813',
    projectId: 'chatterbox-comedy',
    authDomain: 'chatterbox-comedy.firebaseapp.com',
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    databaseURL:
        'https://chatterbox-comedy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterbox-comedy.appspot.com',
=======
    databaseURL: 'https://chatterbox-comedy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterbox-comedy.firebasestorage.app',
>>>>>>> Stashed changes
=======
    databaseURL: 'https://chatterbox-comedy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterbox-comedy.firebasestorage.app',
>>>>>>> Stashed changes
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDDWDB5GcmW1DCXIcK1gaONEaYQhNxC9s',
    appId: '1:136251052813:android:ecac34d4488c153904d644',
    messagingSenderId: '136251052813',
    projectId: 'chatterbox-comedy',
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    databaseURL:
        'https://chatterbox-comedy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterbox-comedy.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDLdlOvy4qpLtIQf49KJCdhd8cAnhS6RPk',
    appId: '1:136251052813:web:8f939ca7b3354c5604d644',
    messagingSenderId: '136251052813',
    projectId: 'chatterbox-comedy',
    authDomain: 'chatterbox-comedy.firebaseapp.com',
    databaseURL:
        'https://chatterbox-comedy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterbox-comedy.appspot.com',
=======
    databaseURL: 'https://chatterbox-comedy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterbox-comedy.firebasestorage.app',
>>>>>>> Stashed changes
=======
    databaseURL: 'https://chatterbox-comedy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterbox-comedy.firebasestorage.app',
>>>>>>> Stashed changes
  );
}
