name: Build Flutter App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
=======
=======
>>>>>>> Stashed changes
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Split APKs
      run: flutter build apk --release --split-per-abi

<<<<<<< Updated upstream
<<<<<<< Updated upstream
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-apks
        path: build/app/outputs/flutter-apk/
=======
=======
>>>>>>> Stashed changes
      - name: Build APK
        run: flutter build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
>>>>>>> Stashed changes
